### ISSUE TITLE
Funny result with my proposal

### ISSUE THREAD

**Issue by RubenVerborgh** [Sindhu-Vasireddy/SolidLoginGreeter#5]
It thinks I'm @dexagod 😃

![image](https://user-images.githubusercontent.com/675313/175565753-09e7a0d6-0933-4f47-9275-fc3e3fed774b.png)

Logged in as https://ruben.verborgh.org/profile/#me

**Comment by Sindhu-Vasireddy** [comment]
Specified webid as the subject for the name query so that it does not pick up on other names. It solves the problem for now.
