### ISSUE TITLE
Add a code linter

### ISSUE THREAD

**Issue by RubenVerborgh** [Sindhu-Vasireddy/SolidLoginGreeter#8]
It helps achieve consistent code, especially with multiple authors.
See for instance https://eslint.org/ and https://github.com/CommunitySolidServer/CommunitySolidServer/blob/main/.eslintrc.js

(I also remarked this on https://github.com/VidyashreeTarikereUgent/solid-todo/issues/17; perhaps we need a quick repo with code guidelines, @pheyvaer?)

**Comment by pheyvaer** [comment]
We mentioned such code guidelines in the past, but we didn't create them because it highly depends on who is developing/supervising the code. Maybe we could revisit it again and put some suggestions together, which would be less strict than guidelines. What do you think?

**Comment by RubenVerborgh** [comment]
I'm happy with some light linting; just anything to have a bit of consistency.

**Comment by Sindhu-Vasireddy** [comment]
Now the code is linted with basic [Eslint Rules](https://github.com/Sindhu-Vasireddy/SolidLoginGreeter/blob/main/.eslintrc.yml) extending google standard Js linting rules for latest ECMA version.
