### ISSUE TITLE
Split code in multiple logical files

### ISSUE THREAD

**Issue by RubenVerborgh** [Sindhu-Vasireddy/SolidLoginGreeter#9]
Currently, business logic and UI are all together in [main.js](https://github.com/Sindhu-Vasireddy/SolidLoginGreeter/blob/main/main.js)

They'd need to be separated such that the business logic can be reused independently of the UI.

Might be interesting/relevant to see how a JavaScript build process can be used to bring all of this together, so that the HTML file does not have to include all individual files. Do ask someone within the team for guidance. For instance, @pheyvaer can explain how https://github.com/KNowledgeOnWebScale/knoodle is set up.

**Comment by Sindhu-Vasireddy** [comment]
The code is now split into Login, UI, Reasoning functionalities and basic utilities (such as solidfetch) in ./src folder. Web assets such as HTML, CSS etc... including the browser eye reasoning elements borrowed from [eyebrow](https://github.com/josd/eyebrow) are placed in ./Public folder.
